### ISSUE TITLE
Main Menu Bar - Sign In/Sign Out Button

### ISSUE THREAD

**Issue by coffeeswap** [iamkhush/coffeeswap#20]
Really like the profile, name + sign out button. However, I tried to see my profile by clicking on my name and it signed me out. Any way we can separate these into two links?

<img width="1274" alt="screen shot 2018-02-27 at 6 21 12 pm" src="https://user-images.githubusercontent.com/29179106/36762848-2ba886aa-1beb-11e8-849b-6485688747d3.png">

**Comment by iamkhush** [comment]
Sure, but what is the requirement here. I can make it more clear by removing the name from the button , so it would just say - SignOut.  
@coffeeswap

**Comment by coffeeswap** [comment]
Let's do that!  "Sign Out"
