### ISSUE TITLE
Logged in user gets stuck

### ISSUE THREAD

**Issue by coffeeswap** [iamkhush/coffeeswap#22]
Here's a fun one:

I'm logged in. If I click on this link: /get-started I get stuck.

You can find/try it here, the link in "How much does it cost?".
<img width="1275" alt="screen shot 2018-02-27 at 6 29 22 pm" src="https://user-images.githubusercontent.com/29179106/36763124-3f2a2890-1bec-11e8-88a2-214b59f32e69.png">

**Comment by iamkhush** [comment]
@coffeeswap the link here is incorrect. Should I link to the signup page , since we dont have a pricing page.

**Comment by coffeeswap** [comment]
That's correct - signup page link (this is also what happens when not logged in)
