### ISSUE TITLE
Sign in/ Sign up modal

### ISSUE THREAD

**Issue by coffeeswap** [iamkhush/coffeeswap#27]
UserName -- change to Username

Is it possible to also allow sign in with email?

<img width="1198" alt="screen shot 2018-04-08 at 11 09 10 am" src="https://user-images.githubusercontent.com/29179106/38469625-78c90076-3b1d-11e8-9138-eceaa81325cc.png">

**Comment by iamkhush** [comment]
Not with email now, since will have to make it unique and will require extra work. I have changed this username change though.
