### ISSUE TITLE
Signing in 

### ISSUE THREAD

**Issue by coffeeswap** [iamkhush/coffeeswap#28]
I think if we have more than one user name that's the same, none of those users will sign in. May need to implement a unique username requirement.

For example, I can't sign in using "Test" as my user name.

When creating a known duplicate user name on the second sign up flow page, the error message copy for the username field should be: "This username seems to be taken - try a different one?"

**Comment by coffeeswap** [comment]
Actually can't sign in using any username/pw combinations

**Comment by iamkhush** [comment]
Can you please check again ? Signin is working for me.

**Comment by coffeeswap** [comment]
It's working, clicking on "My profile" while logged in doesn't work - see other Issue
