### ISSUE TITLE
Google analytics

### ISSUE THREAD

**Issue by coffeeswap** [iamkhush/coffeeswap#29]
This one might be a bit tricky, but at bare minimum it'd be great to have this back up and running. Are you familiar with the requirements for this to work? 

If not, no worries, this may be something I can configure. But will need your help in updating the html.

**Comment by iamkhush** [comment]
yes, I am aware with this. Can you please provide the analytics script or add me to the google analytics project that you have - I will get the script from there.

**Comment by coffeeswap** [comment]
Added you to the project via this email: contact@aoswebsolutions.com
