### ISSUE TITLE
Clicking on "My profile" while logged in redirects to homepage

### ISSUE THREAD

**Issue by coffeeswap** [iamkhush/coffeeswap#31]
Can't view "My profile" when logged in and attempting to access from www.thecoffeeswap.com

**Comment by iamkhush** [comment]
the url should redirect to http://thecoffeeswap.com . 
I am able to check my profile at http://thecoffeeswap.com/profile

**Comment by coffeeswap** [comment]
Ahh - now I can view this page even when I'm not signed in. Can we redirect/force the sign-in modal?

For reference- when not logged in, I can make changes, but when saving it prompts to log in. Can this prompt be moved to a modal not a browser notification?

**Comment by iamkhush** [comment]
Can you please paste the screenshot.
Also, let me know which browser are you using @coffeeswap

**Comment by iamkhush** [comment]
@coffeeswap I found a bug of when user signs up, he is redirected back to home page and when you click on profile, it redirects back again. Please confirm
